version: '3'
services:
  flog-0:
    image: sindonghyun/flog:latest
    container_name: flog
    ports:
      - "8080:8080"
    restart: always
    networks:
      - flog_network
  flog-1:
    image: sindonghyun/flog:latest
    container_name: flog-1
    ports:
      - "8081:8080"
    restart: always
    networks:
      - flog_network
  
networks:
  flog_network:
    external: true
